// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR9aD2okRo-rJqO2HKFnDMjLDSHhlePVM',
    appId: '1:747158692210:web:c7b9b1337a79af7e247deb',
    messagingSenderId: '747158692210',
    projectId: 'newmeet-cb550',
    authDomain: 'newmeet-cb550.firebaseapp.com',
    storageBucket: 'newmeet-cb550.appspot.com',
    measurementId: 'G-J9EFJNHBPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp2a_MiZC1csooAuoQqWxcXgXJY_WudeE',
    appId: '1:747158692210:android:87deddfe40747105247deb',
    messagingSenderId: '747158692210',
    projectId: 'newmeet-cb550',
    storageBucket: 'newmeet-cb550.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOdXSGl-9HMvt2wr0f7Svnz4KCKNVkrSI',
    appId: '1:747158692210:ios:e90240eefa1384df247deb',
    messagingSenderId: '747158692210',
    projectId: 'newmeet-cb550',
    storageBucket: 'newmeet-cb550.appspot.com',
    iosClientId: '747158692210-f0lqurti4q7qukribltju4rb4e9n9kme.apps.googleusercontent.com',
    iosBundleId: 'com.onatcipli.networkUpp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOdXSGl-9HMvt2wr0f7Svnz4KCKNVkrSI',
    appId: '1:747158692210:ios:e90240eefa1384df247deb',
    messagingSenderId: '747158692210',
    projectId: 'newmeet-cb550',
    storageBucket: 'newmeet-cb550.appspot.com',
    iosClientId: '747158692210-f0lqurti4q7qukribltju4rb4e9n9kme.apps.googleusercontent.com',
    iosBundleId: 'com.onatcipli.networkUpp',
  );
}
